### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by KekkyShmekky** [StyledStrike/gmod-gpaint#1]
Lua function below
```JMod.LuaConfig.BuildFuncs["SmallPaintBoard"] = function(ply, position, angles)
    local e = ents.Create("ent_gpaint_075x1")
    e:SetPos(position)
    e:SetAngles(Angle(90, ply:EyeAngles().y, 0))
    e:Spawn()
    e:PhysWake()
    timer.Simple( 0.3, function()
        if not IsValid( e ) then return end

        local owner = e:GetCreator()
        if not IsValid( owner ) then return end

        -- tell the screen owner to subscribe right away
        local gnet = GPaint.network
		
        gnet.StartCommand( gnet.SUBSCRIBE, e )
        net.Send( owner )
    end )
    return e
end

**Comment by StyledStrike** [comment]
My guess is that depending on ping, that delay is not enough to wait for the entity to get initialized client side...
Honestly a much better approach to this is to make the client who created the entity subscribe by themselves once they do initialize, but first I need to find a way to get the entity creator client-side. I'm looking into it.

**Comment by StyledStrike** [comment]
~~As a temporary """fix""", I'll just increase the delay.~~

Nevermind, found a way to do it just now 👀

**Comment by KekkyShmekky** [comment]
Hey so if you've found a way to fix the issue, can you push it to GitHub as well as WS? Thanks!

**Comment by StyledStrike** [comment]
Forgor to close this issue 💀
Anyway, it has been pushed (a while ago)
