### ISSUE TITLE
Screens fail to load post-rejoin

### ISSUE THREAD

**Issue by KekkyShmekky** [StyledStrike/gmod-gpaint#3]
So I managed to figure out how to get boards working outside of Sandbox with the code below, but whenever I rejoin, the boards are stuck on "Loading Image...". I'm wondering if I'm missing something from either of the code below.

garrysmod/lua/autorun/server
```lua
hook.Add("OnEntityCreated","GPaint",function(ent)
        if ent.Base == "ent_gpaint_base" then
            timer.Simple(1,function()
                    if IsValid(ent:GetCreator()) and IsValid(ent) then
                        GPaint.network.StartCommand(GPaint.network.SUBSCRIBE, ent)
                        net.Send(ent:GetCreator())
                    end
                    return ent
                end
            )
        end
    end
)
```
Another example function that I use with Jmod's custom build func feature.
```lua
JMod.LuaConfig.BuildFuncs["SmallPaintBoard"] = function(ply, position, angles)
    local e = ents.Create("ent_gpaint_075x1")
    e:SetPos(position)
    e:SetAngles(Angle(0, ply:EyeAngles().y, 0))
    e:Spawn()
    NADMOD.PlayerMakePropOwner(ply, e)
    e:Activate()
    e:PhysWake()
    e:SetCreator(ply)
   	e:SetGPaintOwner(ply)
   	e:CanPlayerDraw(ply)
    e.GPaintWhitelist = {ply:SteamID()}
end
```

**Comment by StyledStrike** [comment]
The `GPaintOwner` network variable is probably becoming invalid once that player leaves the game. A possible solution is updating it again for existing screens once the player spawns, which would probably require storing the owner's SteamID on each of them.

To be honest, I have not given much thought about supporting this addon in gamemodes other than Sandbox, but I've seen quite a few cases if people trying so, might as well get started 😃 

Unfortunately I can only really help starting tomorrow due to personal reasons. Let me know if ya have any questions!

**Comment by StyledStrike** [comment]
Just leaving a note to myself: a better solution could be replacing the `GPaintOwner`, an entity network variable, with `GPaintOwnerSteamId`, a string network variable.

**Comment by StyledStrike** [comment]
Turns out that, besides using SteamIDs, it also needed to remove disconnected players from the `subscribers` table of each GPaint screen :eyes:

**Comment by StyledStrike** [comment]
Lemme know if any more issues arise from this. Thanks!

<details><summary>A little bit more about the code at the start of this issue...</summary>
<p>
I'd like to clarify a few more things about the code posted by @KekkyShmekky earlier.

- The `OnEntityCreated` hook is called very early, and and such, according to the wiki, *very little of the entity's properties will be initialized at this stage.* This might cause issues with the GPaint owner not being set yet or `GetCreator` being invalid, for example.


- `entity:CanPlayerDraw(ply)` is only supposed to be called if you expect to use it's return value somewhere else.
- The GPaint owner does not need to go into the `GPaintWhitelist` table.
</p>
</details>

**Comment by KekkyShmekky** [comment]
Okay thank you! Testing it now with the hook removed as well as the last 2 lines for every similar buildfunc commented out and removed respectively.

**Comment by KekkyShmekky** [comment]
Hey so as it turns out, with everything uncommented, the screens go right by the first 2 lines of text and can't be used at all.

**Comment by StyledStrike** [comment]
Which are the "first 2 lines" are you refering to? Also, which gamemode are you trying to make them work on?

**Comment by KekkyShmekky** [comment]
> Which are the "first 2 lines" are you refering to? Also, which gamemode are you trying to make them work on?

I'm referring to the "Press E" and "Loading image..." lines, and I'm also using [this gamemode](https://steamcommunity.com/sharedfiles/filedetails/?id=938621855).

**Comment by StyledStrike** [comment]
Hey so, unfortunately I have not been able to replicate that issue. While on *Fort Fights*, as a test, I started a multiplayer game and ran this piece of code to spawn a GPaint screen:
```
local ply = player.GetBySteamID( "<my-steam-id-here>" )
local e = ents.Create( "ent_gpaint_075x1" )

e:SetPos( ply:GetPos() + Vector( 40, 0, 50 ) )
e:SetAngles( Angle( 90, 0, 0 ) )
e:Spawn()
e:Activate()
e:PhysWake()
e:SetCreator( ply )
e:SetGPaintOwner( ply )
```

And it seems to work...
![test](https://github.com/StyledStrike/gmod-gpaint/assets/14253048/a9c836dc-4b31-4009-b9dc-2442baf3316d)

If you can, please share more about the way you're actually spawning them, and what the *environment * of your game looks like (example: are ya on a dedicated server, on a multiplayer game started through gmod's main menu, or on single player, what other addons do ya have installed, **when** ara ya spawning them, etc.)

**Comment by KekkyShmekky** [comment]
Okay so I just managed to get the boards to work by asking another player to test them after applying those last 2 lines of Lua, but the rejoin bug apparently persists in the sense that the screen is blanked out. This is on a dedicated multiplayer server, [these are the addons I'm using including the linked collections](https://steamcommunity.com/sharedfiles/filedetails/?id=1648401086), and the boards are spawned by crafting them with the EZ Toolbox which any player with an engineer kit can do if they have the necessary EZ resources nearby, unless you mean something else by "when".

EDIT: I just restarted the server and I already have the most recent Workshop version of the addon installed as of when the testing occurred.

**Comment by StyledStrike** [comment]
Oh I just want to clarify that, currently, only the clients know what the screens looks like, and (basically) only the owner can provide the latest "content" from their screens. This means that, if any player rejoins while the owner is not on the server, the screens can't provide what their contents are.

In techinical words, the server does not hold screen images at all, it only broadcasts them.

**Comment by KekkyShmekky** [comment]
Okay so how much of a hit would performance take if the server were to start holding screen images in order to fix the issue of clients not seeing them upon rejoin?
