### ISSUE TITLE
Netstream library relies on pac for error messaging

### ISSUE THREAD

**Issue by TankNut** [StyledStrike/gmod-gpaint#5]
https://github.com/StyledStrike/gmod-gpaint/blob/master/lua/autorun/netstream.lua#L38 uses two instances of pac.Message for error messaging, meaning it would error out if PAC isn't installed and netstream errors out.

**Comment by StyledStrike** [comment]
This pushed me to finally do it: I'm currently working on a refactor for the whole addon, and a replacement for netstream is one of the objectives too. I'll get back to ya once it's done.
